name = "Sokenmon Evolved"
author = "Soken"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33a013529dd6186fe769c265bf1633db6eeca78fd6bc81846d48e8d4071e1d2d"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
