name = "Sokenmon Evolved"
author = "Soken"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f355f52c0b032c043ce31414a42aac34fdc99d18b1be06cf8335d3fe54020e3"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
