name = "Sokenmon Evolved"
author = "Soken"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4345b5c2726f620b5a6abb10f2e31dbd4a172c50ec77aae5ec0f2fc22f34f0f7"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
